/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns;

import design.patterns.solution.impl.CurrentConditionDisplay;
import design.patterns.solution.impl.WeatherManager;

/**
 * App is the weather station
 * */
public class App {
    public static void main(String[] args) {
		WeatherManager wm = new WeatherManager();

		wm.registerObserver(new CurrentConditionDisplay());

		wm.setMeasurement(10, 20, 30);
    }
}